# Shifting value for reproduction number
# infection to report delay
r_shift: -11

# Maximum value of reproduction number to consider
max_r: 4

# Minimum number of total official cases to take a country into consideration
min_cases: 500

# Minimum ratio of days with valid R estimation for a country to be considered
min_ratio: 0.9
