# Number of layers
n_layers: 1

# Max number of epochs (if no early stopping)
max_epochs: 300

# Learning rate config
auto_lr_find: True
default_lr: 0.001

# Batch config
auto_scale_batch_size: False
default_batch_size: 64

# Early stopping patience
patience: 25

# Number of past days taken into account for
past_window: 7

# Sizes of hidden layers
hidden_size:
  - 15
  - 15
  - 15

# Droput probability
dropout: 0.2

# Random seed
seed: 42
